# Generated by Django 6.0.3 on 2026-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
